version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: Install pytest
          command: pip install pytest
      - run:
          name: Run tests
          command: python -m pytest
workflows:
  config_flask:
    jobs:
      - test:
          filters:
            branches:
              only: master

